# Generated by Django 4.0.3 on 2022-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stallion_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.CharField(choices=[('Area A ($100)', 'Area A ($100)'), ('Area B ($75)', 'Area B ($75)'), ('Area C ($50)', 'Area C ($50)')], max_length=20),
        ),
    ]
