# Generated by Django 4.0.3 on 2022-04-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stallion_website', '0002_eventticket_ticket_delete_tickets_eventticket_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stallion_website.member')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stallion_website.program')),
            ],
        ),
        migrations.CreateModel(
            name='CourtReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stallion_website.court')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stallion_website.member')),
            ],
        ),
    ]
