# Generated by Django 4.0.3 on 2022-04-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stallion_website', '0002_event_tickets_eventtickets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('datetime', 'location')},
        ),
    ]
