# Generated by Django 4.0.3 on 2022-04-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stallion_website', '0003_court_memberprograms_courtreservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
