# Generated by Django 4.0.3 on 2022-04-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stallion_website', '0004_coach_rename_phonenumber_member_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dates',
            new_name='Date',
        ),
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
