# Generated by Django 4.0.3 on 2022-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stallion_website', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
